# Generated by Django 4.1.4 on 2022-12-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=255)),
                ("product_description", models.CharField(max_length=255)),
                ("about", models.CharField(max_length=255)),
                ("characteristics", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
