# Generated by Django 4.1.4 on 2022-12-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="about", field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(max_length=500),
        ),
    ]
