# Generated by Django 4.1.4 on 2022-12-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tourID', models.AutoField(primary_key=True, serialize=False)),
                ('tourFrom', models.CharField(max_length=255)),
                ('tourTo', models.CharField(max_length=255)),
                ('tourDays', models.IntegerField()),
                ('persons', models.IntegerField()),
            ],
        ),
    ]
