# Generated by Django 4.1.4 on 2022-12-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("sub_plus", models.BooleanField(default=False)),
            ],
        ),
    ]
