# Generated by Django 4.1.4 on 2022-12-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=77059706171, max_length=50),
            preserve_default=False,
        ),
    ]
