# Generated by Django 4.1.4 on 2022-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_favorites",
            field=models.CharField(default=[], max_length=5000),
            preserve_default=False,
        ),
    ]
