# Generated by Django 4.1.4 on 2022-12-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_user_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="user_favorites", new_name="user_basket",
        ),
    ]
