# Generated by Django 4.1.4 on 2022-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_about_alter_product_characteristics_and_more"),
        ("users", "0007_alter_user_user_basket"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="user_basket",),
        migrations.AddField(
            model_name="user",
            name="user_buylist",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
