# Generated by Django 4.1.4 on 2022-12-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_about_alter_product_characteristics_and_more"),
        ("users", "0008_remove_user_user_basket_user_user_buylist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_buylist",
            field=models.ManyToManyField(
                blank=True, related_name="user_buylist", to="products.product"
            ),
        ),
    ]
